#!/usr/bin/env bash

# Easier navigation: .., ..., ...., ....., ~ and -
alias ..="cd .."
alias ...="cd ../.."
alias ....="cd ../../.."
alias .....="cd ../../../.."
alias ~="cd ~" # `cd` is probably faster to type though
alias -- -="cd -"

# List all files colorized in long format
alias l="ls -laFh --color=auto"

# List all files colorized in long format, including dot files
alias la="ls -laFh --color=auto"

# List only directories
alias lsd="ls -lFh --color=auto | grep --color=never '^d'"

# Always use color output for `ls`
alias ls="command ls --color=auto"

# Always enable colored `grep` output
# Note: `GREP_OPTIONS="--color=auto"` is deprecated, hence the alias usage.
alias grep='grep --color=auto'
alias fgrep='fgrep --color=auto'
alias egrep='egrep --color=auto'

# Enable aliases to be sudo’ed
alias sudo='sudo '

# Get week number
alias week='date +%V'

# Stopwatch
alias timer='echo "Timer started. Stop with Ctrl-D." && date && time cat && date'

# IP addresses
alias ip="dig +short myip.opendns.com @resolver1.opendns.com"
alias localip="ipconfig getifaddr en0"
alias ips="ifconfig -a | grep -o 'inet6\? \(addr:\)\?\s\?\(\(\([0-9]\+\.\)\{3\}[0-9]\+\)\|[a-fA-F0-9:]\+\)' | awk '{ sub(/inet6? (addr:)? ?/, \"\"); print }'"

# Show active network interfaces
alias ifactive="ifconfig | pcregrep -M -o '^[^\t:]+:([^\n]|\n\t)*status: active'"

# Flush DNS
alias dnsflush="sudo dscacheutil -flushcache && sudo killall -HUP mDNSResponder && echo 'DNS flushed'"

# Clean up LaunchServices to remove duplicates in the “Open With” menu
alias lscleanup="/System/Library/Frameworks/CoreServices.framework/Frameworks/LaunchServices.framework/Support/lsregister -kill -r -domain local -domain system -domain user && killall Finder"

# View HTTP traffic
alias sniff="sudo ngrep -d 'en1' -t '^(GET|POST) ' 'tcp and port 80'"
alias httpdump="sudo tcpdump -i en1 -n -s 0 -w - | grep -a -o -E \"Host\: .*|GET \/.*\""

# Show/Hide dotfiles
alias show_files="defaults write com.apple.finder AppleShowAllFiles YES && killall Finder /System/Library/CoreServices/Finder.app"
alias hide_files="defaults write com.apple.finder AppleShowAllFiles NO && killall Finder /System/Library/CoreServices/Finder.app"

# Canonical hex dump; some systems have this symlinked
command -v hd > /dev/null || alias hd="hexdump -C"

# macOS has no `md5sum`, so use `md5` as a fallback
command -v md5sum > /dev/null || alias md5sum="md5"

# macOS has no `sha1sum`, so use `shasum` as a fallback
command -v sha1sum > /dev/null || alias sha1sum="shasum"

# Recursively delete `.DS_Store` files
alias cleanup="find . -type f -name '*.DS_Store' -ls -delete"

# Empty the Trash on all mounted volumes and the main HDD.
# Also, clear Apple’s System Logs to improve shell startup speed.
# Finally, clear download history from quarantine. https://mths.be/bum
alias emptytrash="sudo rm -rfv /Volumes/*/.Trashes; sudo rm -rfv ~/.Trash; sudo rm -rfv /private/var/log/asl/*.asl; sqlite3 ~/Library/Preferences/com.apple.LaunchServices.QuarantineEventsV* 'delete from LSQuarantineEvent'"

# Print each PATH entry on a separate line
alias path='echo -e ${PATH//:/\\n}'

# veracrypt commandline
alias veracrypt='/Applications/VeraCrypt.app/Contents/MacOS/Veracrypt'

# git
alias gst='clear && git status'
alias gcm='git checkout main'
alias gc='git checkout'

# Set these aliases only in zsh
if [ -z ${BASH_VERSION} ]; then
	# $BASH is not set, therefore we are probably in a zsh
	# echo "not in a bash" > /dev/null
    alias history='history -i'
fi

# Generic
alias hashes='echo "###############################"'

# Docker
alias d="docker"
# reset docker, clean everything, but don't delete the build cache
# and don't delete images that match certain terms
# We use a function here, not an alias, since that simplifies character escapes
dcd() { echo "### running docker compose down" && docker compose down --remove-orphans \
		&& echo "### pruning docker images" && docker images -a | grep -v redis | grep -v chrome | grep -v postgres | grep -v IMAGE | awk '{print $3}' | xargs docker rmi \
		&& echo "### pruning docker volumes" && docker volume ls | grep -v daito | grep -v 'VOLUME NAME' | awk '{print $2}' | xargs docker volume rm \
		&& echo "### pruning docker containers" && docker container prune -f \
		&& echo "### pruning docker networks" && docker network prune -f }
alias dcb="time dcd && time docker compose build"
alias dce="docker compose exec"
alias dcr="docker compose run -it --rm"
alias dcu="docker compose up"
alias dcub="time dcd && time docker compose up --build --force-recreate --remove-orphans"

# Daito
alias daitoapp='cd ~/Documents/Arbeit/Daito/Code/app'
alias daitoattach='daitoapp && d attach web'
alias daitobash='daitoapp && hashes && echo "STARTING \"bash\" FOR DAITO" && hashes && echo " " && dcr web bash'
alias daitoconsole='daitoapp && dcr web rails c'
alias daitopsql='daitoapp && dcr postgres psql "postgresql://daito:daito@postgres/daito_development"'
alias daitotest='daitoapp && dcd && dcr web ./scripts/fluffy.sh'

# vscode
alias code='/Applications/Visual\ Studio\ Code.app/Contents/MacOS/Electron'

# ansible
# make sure we add the ssh key to ssh-agent so that we have to enter the ssh key password only once
#alias ansible-playbook='ssh-add -l > /dev/null  || ssh-add ~/.ssh/id_dto-retool-upcloud && ansible-playbook'
