#!/usr/bin/env bash

# show current dir in iTerm tab title
# source: https://gist.github.com/phette23/5270658
if [ "$ITERM_SESSION_ID" ]; then
  export PROMPT_COMMAND='echo -ne "\033];${PWD##*/}\007"; ':"$PROMPT_COMMAND";
fi

# prompt
#export PS1="\[\033[36m\]\u\[\033[m\]@\[\033[32m\]\h:\[\033[33;1m\]\w\[\033[m\]\$ "
#export CLICOLOR=1
#
# That was my old prompt. My current prompt is defined in ``.prompt``.

# ls
export LSCOLORS=ExFxBxDxCxegedabagacad

# brew related
export HOMEBREW_CASK_OPTS="--appdir=/Applications --fontdir=/Library/Fonts --qlplugindir=/Library/QuickLook"
export HOMEBREW_NO_ANALYTICS=0
export HOMEBREW_NO_INSECURE_REDIRECT=1
export HOMEBREW_NO_INSTALL_CLEANUP=1

# shellcheck disable=SC2155
export PATH=$(brew --prefix)/bin:$(brew --prefix)/sbin:$PATH
# path for Homebrew coreutils$(brew --prefix coreutils)/libexec/gnubin
# shellcheck disable=SC2155
export PATH=$(brew --prefix coreutils)/libexec/gnubin:${PATH}

# Make nano the default editor.
export EDITOR='nano';

# Increase Bash history size. Allow 32³ entries; the default is 500.
export HISTSIZE='32768';
export HISTFILESIZE="${HISTSIZE}";
# Omit duplicates and commands that begin with a space from history.
export HISTCONTROL='ignoreboth';
export HISTTIMEFORMAT="%Y-%m-%d %T "

# Prefer US English and use UTF-8.
export LANG='en_US.UTF-8';
export LC_ALL='en_US.UTF-8';
export LC_CTYPE=en_US.UTF-8;

# Don’t clear the screen after quitting a manual page.
export MANPAGER='less -X';

# ruby
export PATH=/Users/jan/.rbenv/shims:$PATH
export optflags="-Wno-error=implicit-function-declaration"
export CFLAGS="-Wno-error=implicit-function-declaration"
export LDFLAGS="-L/usr/local/opt/libffi/lib $LDFLAGS"
export CPPFLAGS="-I/usr/local/opt/libffi/include $CPPFLAGS"
export PKG_CONFIG_PATH="/usr/local/opt/libffi/lib/pkgconfig:$PKG_CONFIG_PATH"
export CONFIGURE_OPTS="--with-openssl-dir=$(brew --prefix openssl@1.1)"

# ruby-build
export RUBY_CONFIGURE_OPTS="--with-openssl-dir=$(brew --prefix openssl@1.1) --with-readline-dir=$(brew --prefix readline) --with-libyaml-dir=$(brew --prefix libyaml) --with-zlib-dir=$(brew --prefix zlib)"

# ruby - readline needs this
export LDFLAGS="-L/usr/local/opt/readline/lib $LDFLAGS"
export CPPFLAGS="-I/usr/local/opt/readline/include $CPPFLAGS"
export PKG_CONFIG_PATH="/usr/local/opt/readline/lib/pkgconfig:$PKG_CONFIG_PATH"

# ruby  - openssl needs this
export LDFLAGS="-L/usr/local/opt/openssl@1.1/lib $LDFLAGS"
export CPPFLAGS="-I/usr/local/opt/openssl@1.1/include $CPPFLAGS"
export PKG_CONFIG_PATH="/usr/local/opt/openssl@1.1/lib/pkgconfig:$PKG_CONFIG_PATH"
export PATH="/usr/local/opt/openssl@1.1/bin:$PATH"

#pyenv for python
export PYENV_ROOT="$HOME/.pyenv"
export PATH="$PYENV_ROOT/bin:$PATH"
export PATH="$HOME/.local/bin:$PATH"
eval "$(pyenv init --path)"

# postgres
export PATH="/usr/local/opt/postgresql@15/bin:$PATH"
export LDFLAGS="-L/usr/local/opt/postgresql@15/lib $LDFLAGS"
export CPPFLAGS="-I/usr/local/opt/postgresql@15/include $CPPFLAGS"
export PKG_CONFIG_PATH="/usr/local/opt/postgresql@15/lib/pkgconfig"
# libq
export PATH="/usr/local/opt/libpq/bin:$PATH"
export LDFLAGS="-L/usr/local/opt/libpq/lib"
export CPPFLAGS="-I/usr/local/opt/libpq/include"
export PKG_CONFIG_PATH="/usr/local/opt/libpq/lib/pkgconfig"

# Fix Ansible
export ANSIBLE_PYTHON_INTERPRETER="$(which python)"

# Add `~/bin` to the `$PATH`
export PATH=${HOME}/bin:${PATH}

# node
# Enable persistent REPL history for `node`.
export NODE_REPL_HISTORY=~/.node_history;
# Allow 32³ entries; the default is 1000.
export NODE_REPL_HISTORY_SIZE='32768';
# Use sloppy mode by default, matching web browsers.
export NODE_REPL_MODE='sloppy';
export PATH="$PATH:./node_modules/.bin"

export NVM_DIR="$HOME/.nvm"
[ -s "/usr/local/opt/nvm/nvm.sh" ] && \. "/usr/local/opt/nvm/nvm.sh"  # This loads nvm

# remove duplicate PATH entries
# and finally export one last time
export PATH=$(echo "$PATH" | awk -v RS=':' -v ORS=":" '!a[$1]++{if (NR > 1) printf ORS; printf $a[$1]}')

# dump your path like this
# echo $PATH | tr ':' '\n'. | sort

# Remove annoying warning that I should switch to zsh
# https://support.apple.com/en-us/HT208050
export BASH_SILENCE_DEPRECATION_WARNING=1

# Needed for GPG and e.g. signing commits
export GPG_TTY=$(tty)
